version: 0.2

phases:

  pre_build:
      commands: 
        
  build:
      commands: 
          
          - make install CI=true
          - make global-install
          - make build
          # - npm run test-cov        

  post_build:
      commands:
        - mv ./appspec.yml ./build
        - find . ! -regex '^./build\(/.*\)?' -delete
        - mv ./build/* .
        - rm -rf ./build 
artifacts:
  files:
    - '**/*'
