version: 0.2

phases:

  pre_build:
      commands: 
        
  build:
      commands: 
          
          - npm install
          - npm install -g babel
          - npm install -g eslint
          - npm install -g babel-eslint
          - npm install -g eslint-plugin-react
          - npm install -g eslint-plugin-json
          - npm run build        
  
  post_build:
      commands:
       
artifacts:
  files:
    - '**/*'
    